name: Feature Engineering

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'   # hourly

jobs:
  feature-engineering:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: pip install -r requirements.txt
      - name: Fetch latest data (hourly, skip if no new data)
        env:
          HOPSWORKS_API_KEY: ${{ secrets.HOPSWORKS_API_KEY }}
        run: python data_engineering/fetch_data.py --hourly
      - name: Preprocess raw data
        run: python data_engineering/preprocess.py
      - name: Generate features (if new data)
        run: python feature_engineering/generate_features.py
