name: Feature Engineering

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 3 * * *'   # daily 03:00 UTC

jobs:
  feature-engineering:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install deps
        run: pip install -r requirements.txt
      - name: Run pipeline
        env:
          HOPSWORKS_API_KEY: ${{ secrets.HOPSWORKS_API_KEY }}
        run: |
          python data_engineering/fetch_data.py --year $(date -u +%Y) --month $(date -u +%m)
          python feature_engineering/generate_features.py
