name: Feature Engineering

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'  # runs at the top of every hour

jobs:
  feature-engineering:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Fetch latest data (skip if no new data)
        env:
          HOPSWORKS_API_KEY: ${{ secrets.HOPSWORKS_API_KEY }}
        run: |
          echo "Fetching data..."
          python data_engineering/fetch_data.py --hourly

      - name: Preprocess raw data
        run: |
          echo "Preprocessing data..."
          python data_engineering/preprocess.py

      - name: Generate features (only if new data exists)
        env:
          HOPSWORKS_API_KEY: ${{ secrets.HOPSWORKS_API_KEY }}
        run: |
          echo "Generating features..."
          python feature_engineering/generate_features.py
