name: Fetch Latest Data

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'  # runs at the top of every hour

jobs:
  fetch-latest-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        run: pip install -r requirements.txt

      - name: Fetch latest data (skip if no new data)
        env:
          HOPSWORKS_API_KEY: ${{ secrets.HOPSWORKS_API_KEY }}
        run: |
          echo "Starting hourly data fetch..."
          python data_engineering/fetch_data.py --hourly
